### ISSUE TITLE
DaemonSet Pods Can't Connect to etcd

### ISSUE THREAD

**Issue by HarishKM7** [ondat/charts#42]
# Steps to Reproduce the Issue

```
helm install ondat ondat/ondat \
--create-namespace --namespace storageos \
--set etcd-cluster-operator.cluster.namespace=storageos-etcd \
--set etcd-cluster-operator.cluster.replicas=3 \
--set etcd-cluster-operator.cluster.storageclass=gp3
```

# Expected Result
All pods in `storageos` & `storageos-etcd` namespace should be healthy.

# Actual Result
All pods of the `storageos-node` DaemonSet in the `storageos` namespace are in `CrashLoopBackOff` because their `storageos` container never becomes healthy. Container logs indicate that they're unable to connect to `etcd`.

# Root Cause
`ETCD_ENDPOINTS` in the `storageos-node` ConfigMap is set to `storageos-etcd.storageos:2379` instead of `storageos-etcd.storageos-etcd:2379`. Fixing this manually doesn't work because `ETCD_ENDPOINTS` is reset to `storageos-etcd.storageos:2379` in a few seconds.

# Workaround
Install `etcd` in the same namespace as everything else:

```
helm install ondat ondat/ondat \
--create-namespace --namespace storageos \
--set etcd-cluster-operator.cluster.replicas=3 \
--set etcd-cluster-operator.cluster.storageclass=gp3
```

**Comment by aeroniero33** [comment]
Hi @HarishKM7 , if the ETCD namespace is different than the namespace Ondat is installed on, then the `ondat-operator.cluster.kvBackend.namespace` [value](https://github.com/ondat/charts/blob/main/charts/ondat-operator/values.yaml#L157) needs to be set as well. It is the value that sets the kvBackend address, that allows Ondat to connect to ETCD.

The Ondat Umbrella chart currently uses the [ondat-operator ](https://github.com/ondat/charts/tree/main/charts/ondat-operator) and [etcd-cluster-operator](https://github.com/ondat/charts/tree/main/charts/etcd-cluster-operator) component charts. These charts currently don't share their values, so the above value needs to be set. I will discuss with the team on how to make this process more intuitive, so thank you for raising it!

**Comment by HarishKM7** [comment]
Thanks @aeroniero33. Please add `ondat-operator.cluster.kvBackend.namespace` to the `helm install` command in [Ondat's quick start guide](https://docs.ondat.io/docs/install/quick-start-guide/#step-3---customise-and-install-the-helm-chart) so others don't encounter this issue.
